[package]
name = "esp-idf-svc"
version = "0.30.0"
authors = ["Ivan Markov <ivan.markov@gmail.com>"]
edition = "2018"
resolver = "2"
categories = ["embedded", "hardware-support"]
keywords = ["embedded", "svc", "idf", "esp-idf", "esp32"]
description = "Implementation of the embedded-svc traits for ESP-IDF (Espressif's IoT Development Framework)"
repository = "https://github.com/esp-rs/esp-idf-svc"
license = "MIT OR Apache-2.0"
readme = "README.md"

[patch.crates-io]
smol = { git = "https://github.com/esp-rs-compat/smol" }
polling = { git = "https://github.com/esp-rs-compat/polling" }
socket2 = { git = "https://github.com/esp-rs-compat/socket2" }
getrandom = { version = "0.2", git = "https://github.com/esp-rs-compat/getrandom.git" }
#getrandom1 = { version = "0.1", git = "https://github.com/esp-rs-compat/getrandom.git", package = "getrandom", branch = "0.1" }
embedded-svc = { path = "../embedded-svc" }
esp-idf-svc = { path = "../esp-idf-svc" }

[features]
default = ["std", "experimental"]

std = ["alloc", "anyhow/std", "log/std", "esp-idf-sys/std", "esp-idf-hal/std", "embedded-svc/std"]
alloc = ["cstr_core/alloc", "anyhow", "embedded-svc/alloc"]

experimental = ["embedded-svc/experimental"]

[dependencies]
enumset = { version = "1", default-features = false }
log = { version = "0.4", default-features = false }
cstr_core = "0.2"
anyhow = { version = "1", default-features = false, optional = true }
mutex-trait = "0.2"
embedded-svc = { version = "0.13", default-features = false }
esp-idf-sys = { version = "0.25", default-features = false, features = ["pio"] }
esp-idf-hal = { version = "0.25", default-features = false, features = ["esp-idf-sys"] }

[build-dependencies]
embuild = "0.25"
anyhow = "1"
